development:
  adapter: redis
  url: redis://redis:6379/2
  channel_prefix: webapp_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: webapp_production
